### ISSUE TITLE
Better index page (collection)

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#110]
- [x] List of workspaces should be on homepage (again) #105 
- [x] Make UI a little prettier #94
- [x] Pointers aren't rendered correctly on root page #106
- [x] Consider showing scratchpad on index page as description #109
- [x] Show loading indicator while workspaces are loading #104
- [x] Don't show budget on index page #107
- [x] Sort workspaces on index page #108
- [x] Prominently link to tree view from index page #116
